Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -57,16 +57,21 @@ jobs:
       # ------------------------------------------
       - name: Build MTA Archive
         run: mbt build -p=cf # Builds the .mtar file at the repository root
-
       - name: Get Source Subaccount Details
         id: source_details
         run: |
+          set -e
           # Login using username/password
           btp login \
           --url "https://cpcli.cf.eu10.hana.ondemand.com" \
           --user "${{ secrets.CF_USERNAME_DEV }}" \
           --password "${{ secrets.CF_PASSWORD_DEV }}"
-          && btp target --global-account b341954b-b853-4249-854c-e5d960dec889 --subaccount 07d04ce0-4e6e-4c34-9476-325191a3ade5
+          --global-account "b341954b-b853-4249-854c-e5d960dec889"
+          --subaccount "07d04ce0-4e6e-4c34-9476-325191a3ade5"
+          if [ $? -ne 0 ]; then
+            echo "Error: The btp command failed or returned no JSON."
+            exit 1
+          fi
 
           SOURCE_SUBACCOUNT_INFO=$(btp get accounts/subaccount "07d04ce0-4e6e-4c34-9476-325191a3ade5")
 
